# Generated by Django 5.0.7 on 2024-09-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JugadorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=100)),
                ('nation', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('matchesPlayed', models.IntegerField()),
                ('starts', models.IntegerField()),
                ('minutesPlayed', models.IntegerField()),
                ('nineties', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('goalsPlusAssists', models.IntegerField()),
                ('goalsMinusPenalties', models.IntegerField()),
                ('penalties', models.IntegerField()),
                ('penaltiesAttempted', models.IntegerField()),
                ('yellowCards', models.IntegerField()),
                ('redCards', models.IntegerField()),
                ('expectedGoals', models.FloatField()),
                ('nonPenaltyExpectedGoals', models.FloatField()),
                ('expectedAssists', models.FloatField()),
                ('nonPenaltyGoalsPlusExpectedAssists', models.FloatField()),
                ('progressiveCarries', models.IntegerField()),
                ('progressivePasses', models.IntegerField()),
                ('progressivePassesReceived', models.IntegerField()),
                ('goalsPerNinety', models.FloatField()),
                ('assistsPerNinety', models.FloatField()),
                ('goalsPlusAssistsPerNinety', models.FloatField()),
                ('goalsMinusPenaltiesPerNinety', models.FloatField()),
                ('goalsPlusAssistsMinusPenaltiesPerNinety', models.FloatField()),
                ('expectedGoalsPerNinety', models.FloatField()),
                ('expectedAssistsPerNinety', models.FloatField()),
                ('expectedGoalsPlusAssistsPerNinety', models.FloatField()),
                ('nonPenaltyExpectedGoalsPerNinety', models.FloatField()),
                ('nonPenaltyGoalsPlusExpectedAssistsPerNinety', models.FloatField()),
            ],
        ),
    ]
