# Generated by Django 5.0.7 on 2024-09-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadormodel',
            name='minutesPlayed',
            field=models.FloatField(),
        ),
    ]
