# Generated by Django 5.0.7 on 2024-08-06 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='estadisticas',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.statisticsmodel'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='jugador',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.playermodel'),
        ),
        migrations.AddField(
            model_name='playermodel',
            name='birth',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.birthmodel'),
        ),
        migrations.AddField(
            model_name='statisticsmodel',
            name='cards',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cardsmodel'),
        ),
        migrations.AddField(
            model_name='statisticsmodel',
            name='dribbles',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.dribblesmodel'),
        ),
        migrations.AddField(
            model_name='statisticsmodel',
            name='duels',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.duelsmodel'),
        ),
        migrations.AddField(
            model_name='statisticsmodel',
            name='fouls',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.foulsmodel'),
        ),
        migrations.AddField(
            model_name='statisticsmodel',
            name='games',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.gamesmodel'),
        ),
        migrations.AddField(
            model_name='statisticsmodel',
            name='goals',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.goalsmodel'),
        ),
        migrations.AddField(
            model_name='statisticsmodel',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.leaguemodel'),
        ),
        migrations.AddField(
            model_name='statisticsmodel',
            name='passes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.passesmodel'),
        ),
        migrations.AddField(
            model_name='statisticsmodel',
            name='penalty',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.penaltymodel'),
        ),
        migrations.AddField(
            model_name='statisticsmodel',
            name='shots',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.shotsmodel'),
        ),
        migrations.AddField(
            model_name='statisticsmodel',
            name='substitutes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.substitutesmodel'),
        ),
        migrations.AddField(
            model_name='statisticsmodel',
            name='tackles',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tacklesmodel'),
        ),
        migrations.AddField(
            model_name='statisticsmodel',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.teammodel'),
        ),
        migrations.AlterField(
            model_name='birthmodel',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='birthmodel',
            name='date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='birthmodel',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cardsmodel',
            name='red',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardsmodel',
            name='yellow',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardsmodel',
            name='yellowred',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dribblesmodel',
            name='attempts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dribblesmodel',
            name='past',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dribblesmodel',
            name='success',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duelsmodel',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duelsmodel',
            name='won',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foulsmodel',
            name='committed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foulsmodel',
            name='drawn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesmodel',
            name='appearences',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesmodel',
            name='captain',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesmodel',
            name='lineups',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesmodel',
            name='minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesmodel',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesmodel',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gamesmodel',
            name='rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='goalsmodel',
            name='assists',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goalsmodel',
            name='conceded',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goalsmodel',
            name='saves',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goalsmodel',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaguemodel',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leaguemodel',
            name='flag',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaguemodel',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaguemodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='passesmodel',
            name='accuracy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passesmodel',
            name='key',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passesmodel',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='penaltymodel',
            name='commited',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='penaltymodel',
            name='missed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='penaltymodel',
            name='saved',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='penaltymodel',
            name='scored',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='penaltymodel',
            name='won',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='firstname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='height',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='injured',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='lastname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='weight',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='shotsmodel',
            name='on',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shotsmodel',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='substitutesmodel',
            name='bench',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='substitutesmodel',
            name='subbed_in',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='substitutesmodel',
            name='subbed_out',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tacklesmodel',
            name='blocks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tacklesmodel',
            name='interceptions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tacklesmodel',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
