# Generated by Django 5.0.7 on 2024-08-20 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_jugador_estadisticas_jugador_jugador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playermodel',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='statisticsmodel',
            name='cards',
        ),
        migrations.RemoveField(
            model_name='statisticsmodel',
            name='dribbles',
        ),
        migrations.RemoveField(
            model_name='statisticsmodel',
            name='duels',
        ),
        migrations.RemoveField(
            model_name='statisticsmodel',
            name='fouls',
        ),
        migrations.RemoveField(
            model_name='statisticsmodel',
            name='games',
        ),
        migrations.RemoveField(
            model_name='statisticsmodel',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='estadisticas',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='jugador',
        ),
        migrations.RemoveField(
            model_name='statisticsmodel',
            name='passes',
        ),
        migrations.RemoveField(
            model_name='statisticsmodel',
            name='penalty',
        ),
        migrations.RemoveField(
            model_name='statisticsmodel',
            name='shots',
        ),
        migrations.RemoveField(
            model_name='statisticsmodel',
            name='substitutes',
        ),
        migrations.RemoveField(
            model_name='statisticsmodel',
            name='tackles',
        ),
        migrations.AddField(
            model_name='leaguemodel',
            name='season',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playermodel',
            name='birth_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statisticsmodel',
            name='captain',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='statisticsmodel',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.playermodel'),
        ),
        migrations.AddField(
            model_name='statisticsmodel',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='statisticsmodel',
            name='statistics',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='BirthModel',
        ),
        migrations.DeleteModel(
            name='CardsModel',
        ),
        migrations.DeleteModel(
            name='DribblesModel',
        ),
        migrations.DeleteModel(
            name='DuelsModel',
        ),
        migrations.DeleteModel(
            name='FoulsModel',
        ),
        migrations.DeleteModel(
            name='GamesModel',
        ),
        migrations.DeleteModel(
            name='GoalsModel',
        ),
        migrations.DeleteModel(
            name='Jugador',
        ),
        migrations.DeleteModel(
            name='PassesModel',
        ),
        migrations.DeleteModel(
            name='PenaltyModel',
        ),
        migrations.DeleteModel(
            name='ShotsModel',
        ),
        migrations.DeleteModel(
            name='SubstitutesModel',
        ),
        migrations.DeleteModel(
            name='TacklesModel',
        ),
    ]
