# Generated by Django 5.0.7 on 2024-09-08 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_defensiveactions_goalandshotcreation_goalkeeperstats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defensiveactions',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.jugadormodel'),
        ),
        migrations.AlterField(
            model_name='goalandshotcreation',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.jugadormodel'),
        ),
        migrations.AlterField(
            model_name='goalkeeperstats',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.jugadormodel'),
        ),
        migrations.AlterField(
            model_name='passing',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.jugadormodel'),
        ),
        migrations.AlterField(
            model_name='passtypes',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.jugadormodel'),
        ),
        migrations.AlterField(
            model_name='shootingmodel',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.jugadormodel'),
        ),
    ]
