# Generated by Django 5.0.7 on 2024-08-20 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_playermodel_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statisticsmodel',
            name='captain',
        ),
        migrations.RemoveField(
            model_name='statisticsmodel',
            name='player',
        ),
        migrations.RemoveField(
            model_name='statisticsmodel',
            name='position',
        ),
        migrations.AddField(
            model_name='playermodel',
            name='stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.statisticsmodel'),
        ),
    ]
