# Generated by Django 5.0.7 on 2024-09-08 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_defensiveactions_player_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goalkeeperstats',
            old_name='passCompletionPercentage',
            new_name='launchCompletionPercentage',
        ),
        migrations.RenameField(
            model_name='goalkeeperstats',
            old_name='passesAttempted',
            new_name='launchedAttempted',
        ),
        migrations.RenameField(
            model_name='goalkeeperstats',
            old_name='passesCompleted',
            new_name='launchedCompleted',
        ),
    ]
