# Generated by Django 5.0.7 on 2024-08-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_statisticsmodel_captain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playermodel',
            name='stats',
        ),
        migrations.AddField(
            model_name='playermodel',
            name='stats',
            field=models.ManyToManyField(blank=True, null=True, to='app.statisticsmodel'),
        ),
    ]
