# Generated by Django 5.0.7 on 2024-09-13 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_passcompletionpercentage_goalkeeperstats_launchcompletionpercentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Possession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('touches', models.IntegerField()),
                ('touchesPenaltyArea', models.IntegerField()),
                ('touchesDefense', models.IntegerField()),
                ('touchesMiddle', models.IntegerField()),
                ('touchesOffense', models.IntegerField()),
                ('touchesOpponentPenaltyArea', models.IntegerField()),
                ('touchesLiveBall', models.IntegerField()),
                ('takeOnAttempted', models.IntegerField()),
                ('takeOnSuccesful', models.IntegerField()),
                ('takeOnSuccesfulPorcentage', models.FloatField()),
                ('takeOnTackled', models.IntegerField()),
                ('takeOnTackledPorcentage', models.FloatField()),
                ('carries', models.IntegerField()),
                ('carriesTotalDistance', models.IntegerField()),
                ('carriesProgressiveDistance', models.IntegerField()),
                ('progressiveCarries', models.IntegerField()),
                ('carriesIntoFinalThird', models.IntegerField()),
                ('carriesIntoPenaltyArea', models.IntegerField()),
                ('miscontrols', models.IntegerField()),
                ('dispossessed', models.IntegerField()),
                ('passesReceived', models.IntegerField()),
                ('passesReceivedProgressive', models.IntegerField()),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.jugadormodel')),
            ],
        ),
    ]
