# Generated by Django 5.0.7 on 2024-09-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_possession'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadormodel',
            name='photo',
            field=models.URLField(null=True),
        ),
    ]
