# Generated by Django 5.0.7 on 2024-11-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_jugadormodel_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=255)),
                ('jersey_number', models.IntegerField()),
                ('position', models.CharField(max_length=50)),
                ('is_substitute', models.BooleanField()),
                ('statistics', models.JSONField()),
                ('is_captain', models.BooleanField()),
                ('team', models.CharField(max_length=10)),
                ('player_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
