# Generated by Django 5.0.7 on 2024-11-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_matchdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchdata',
            name='statistics',
        ),
        migrations.AddField(
            model_name='matchdata',
            name='minutes_played',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchdata',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
