# Generated by Django 5.0.7 on 2024-11-25 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_matchdata_statistics_matchdata_minutes_played_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdata',
            name='jugador',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.jugadormodel'),
        ),
        migrations.AlterField(
            model_name='jugadormodel',
            name='player',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
