# Generated by Django 5.0.7 on 2024-11-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_matchdata_jugador_alter_jugadormodel_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadormodel',
            name='team',
            field=models.TextField(null=True),
        ),
    ]
